# Wine Table Generator using tinytable
#
# This script demonstrates advanced tinytable features to create a visually rich wine table.
# It showcases plot_tt() for embedding images, raw HTML in data cells, and custom styling.
#
# tinytable Column Implementation:
# 1. Bottle Image (empty header): Uses plot_tt() to insert bottle PNG images from local files into data cells
# 2. Wine Name: Plain text data with vintage years extracted and moved to domain_year column
# 3. Domain & Year: Raw HTML with <br> tags embedded in data cells for line breaks
# 4. Region: Raw HTML combining Unicode flag symbols and region text with CSS styling
# 5. Grapes: Raw HTML generated by draw_grapes() function, embedding grape PNG images via <img> tags
# 6. Food Pairings: Raw HTML generated by draw_pairings() function, embedding pairing SVG icons via <img> tags
# 7. Rating: Raw HTML with Unicode stars (⭐), CSS styling, and <br> tags for multi-line display
# 8. Price ($): Numeric data formatted using format_tt() with scales::label_currency()
# 9. Alcohol Content (%): Numeric data formatted using format_tt() with scales::label_percent()
#
# Key tinytable features used:
# - plot_tt(): Inserts column header SVG icons and bottle images into table cells
# - format_tt(): Applies currency and percentage formatting to numeric columns
# - style_tt(): Controls alignment, colors, fonts, and table borders
# - Raw HTML in data cells: Enables custom styling and embedded images
#
# The code used to create this table was adapted to use the [`tinytable`](https://vincentarelbundock.github.io/tinytable/) package in R, based on code originally written by [Abdoul Madjid](https://www.abdoulblog.com) ([GitHub](https://github.com/AbdoulMa)) as a [submission to the RStudio Table Contest 2021](https://posit.co/blog/rstudio-table-contest-2021/), with the original code available on [GitHub](https://github.com/AbdoulMa/RStudio-Table-Contest-2021). The table uses data on some of the world’s most prestigious wines from [Vivino](https://www.vivino.com/), including names, vintages, grape varieties, regions, prices, ratings, allergens, and food pairings, along with the original icons and visual elements.


library(tinytable)
library(countrycode)


# Read and clean input data
clean_input_data <- function(wines_df) {
  df <- wines_df

  # year token and cleaned wine_name
  m <- regexpr("(\\d{4}|N\\.V)", df$wine_name, perl = TRUE)
  df$wine_year <- ifelse(m > 0, regmatches(df$wine_name, m), NA_character_)
  df$wine_name <- sub("\\s(\\d{4}|N\\.V)$", "", df$wine_name, perl = TRUE)

  # ratings
  df$wine_rating <- as.numeric(sub(",", ".", df$wine_rating))
  df$wine_rating_nb <- trimws(sub("notes", "", df$wine_rating_nb, perl = TRUE))

  # bottle_price: keep digits/comma/dot/sign, normalize comma, numeric
  bp <- gsub("\\s+", "", df$bottle_price, perl = TRUE)
  bp <- gsub("[^0-9,.-]", "", bp, perl = TRUE)
  bp <- gsub(",", ".", bp, perl = TRUE)
  df$bottle_price <- suppressWarnings(as.numeric(bp))
  df$bottle_price_dollar <- ceiling((df$bottle_price * 1.16068) / 5) * 5

  # alcohol_content: strip %, normalize comma, numeric
  ac <- gsub("%", "", df$alcohol_content, fixed = TRUE)
  ac <- gsub("[^0-9,.-]", "", ac, perl = TRUE)
  ac <- gsub(",", ".", ac, perl = TRUE)
  df$alcohol_content <- suppressWarnings(as.numeric(ac))

  df <- stats::na.omit(df)
  rownames(df) <- NULL
  df
}


wines <- read.csv("data/wines_top100.csv") |>
  clean_input_data()


# subset and sort
df <- wines[c(1:4, 7:9), , drop = FALSE]
df <- df[order(-df$wine_rating, -df$bottle_price_dollar), ]


## download bottle images
# for (i in seq_len(nrow(df))) {
#   src <- df$bottle_image[i]
#   tar <- file.path("data/bottles", basename(src))
#   download.file(src, tar)
# }
df$bottle_image <- file.path("data/bottles", basename(df$bottle_image))


# helper functions
slugify <- function(x) {
  x <- gsub("[^[:alnum:] ]", "", x)
  x <- gsub(" ", "_", x)
  x <- tolower(x)
  return(x)
}

side_by_side_images <- function(file_paths, height, margin = "1px") {
  if (length(file_paths) == 0 || all(is.na(file_paths))) {
    return("")
  }
  file_paths <- file_paths[!is.na(file_paths)]
  img_tags <- paste0('<img src="', file_paths, '" height="', height, '" style="margin:', margin, ';"/>', collapse = "")
  return(img_tags)
}


# domain & year
df$domain_year <- sprintf("%s<br>%s", df$viticultural_domain, df$wine_year)


# stars
star <- '<span style="color: #FFD700;">⭐</span>'
rating <- '<span style="font-weight: bold; font-size: 1.5em;">%.1f</span>'
rating <- sprintf(rating, df$wine_rating)
df$rating <- sprintf(
  "%s<br>%s<br>%s reviews",
  rating,
  sapply(round(df$wine_rating), \(x) strrep(star, x)),
  df$wine_rating_nb)


# grapes
draw_grapes <- function(grapes, height = 60, margin = "1px") {
  # map variety name -> image path (fallback to others.png)
  get_grape_image <- function(grape_variety) {
    default <- file.path("data", "grapes", "others.png")
    candidate <- file.path("data", "grapes", paste0(grape_variety, ".png"))
    if (file.exists(candidate)) candidate else default
  }

  # remove percentages like "85 % " or "85% ", trim, split on commas, take first 4
  clean <- trimws(gsub("[0-9]|%", "", grapes))
  parts <- strsplit(clean, ",", perl = TRUE)[[1]]
  parts <- gsub("^_+|_+$", "", slugify(parts), perl = TRUE)
  parts <- head(unique(parts), 4)

  # get image paths and return HTML string
  image_paths <- sapply(parts, get_grape_image, USE.NAMES = FALSE)
  side_by_side_images(image_paths, height, margin)
}
df$grapes <- sapply(df$grape_variety, draw_grapes)


# pairings
food_to_icon <- c(
  "Agneau" = "agneau.svg",
  "Apéritif" = "apéritif.svg",
  "Apéritif et snacks" = "apéritif_et_snacks.svg",
  "Bœuf" = "bœuf.svg",
  "Champignons" = "champignons.svg",
  "Crustacés" = "crustacés.svg",
  "Desserts fruités" = "desserts_fruités.svg",
  "Desserts sucrés" = "desserts_sucrés.svg",
  "Fromage affiné et à pâte dure" = "fromage_affiné_et_à_pâte_dure.svg",
  "Fromage bleu" = "fromage_bleu.svg",
  "Fromage de chèvre" = "fromage_de_chèvre.svg",
  "Fromage doux et à pâte molle" = "fromage_doux_et_à_pâte_molle.svg",
  "Gibier" = "gibier.svg",
  "Mets épicés" = "mets_épicés.svg",
  "N'importe quelle camelote alimentaire fera l'affaire" = "n'importe_quelle_camelote_alimentaire_fera_l'affaire.svg",
  "Poisson gras" = "poisson_gras.svg",
  "Poisson maigre" = "poisson_maigre.svg",
  "Porc" = "porc.svg",
  "Pâtes" = "pâtes.svg",
  "Veau" = "veau.svg",
  "Viande assaisonnée" = "viande_assaisonnée.svg",
  "Volaille" = "volaille.svg",
  "Végétarien" = "végétarien.svg"
)

draw_pairings <- function(pairing, icon_height = 40, margin = "2px") {
  pairing_clean <- gsub("\\(.*?\\)", "", pairing, perl = TRUE)
  pairing_items <- trimws(strsplit(pairing_clean, ",", fixed = FALSE)[[1]])

  icons <- vapply(pairing_items, function(item) {
    icon_file <- food_to_icon[[item]]
    if (!is.na(icon_file)) {
      file.path("data", "pairings", icon_file)
    } else {
      file.path("data", "pairings", paste0(item, ".svg"))
    }
  }, character(1L))

  # drop any NA results and return HTML string
  icons <- icons[!is.na(icons)]
  side_by_side_images(icons, icon_height, margin)
}
df$pairings <- sapply(df$food_pairing, draw_pairings)


# regions
regions <- strsplit(df$region, "/", fixed = TRUE)
countries <- sapply(regions, \(x) trimws(x[[1]]))
regions <- sapply(regions, \(x) trimws(x[[2]]))
flags <- countryname(countries, "unicode.symbol")
df$region <- sprintf('<span style="font-size: 2.5em;">%s</span><br>%s', flags, regions)


# final table data (column order + header tweak)
cols <- c("bottle_image", "wine_name", "domain_year", "region", "grapes", "pairings", "rating", "bottle_price_dollar", "alcohol_content")
tbl <- df[, cols]
colnames(tbl)[1] <- "" # empty first header


# icons in column names
bottle_images_data <- df$bottle_image
header_icons <- file.path(
  "data/columns",
  c(
    "wine_glass.svg", "domain.svg", "region.svg", "grape.svg",
    "foods_pairing.svg", "star.svg", "price.svg", "alcohol_content.svg")
)


# draw the table
tab <- tt(tbl,
  caption = "<span style='font-style: italic; font-size: 1.5em;'>Exceptional Wines</span><br>Great wines improve with age. Let's dive into some of the most extraordinary cuvées in the world. Those whose grapes possess ethereal aromas and pure minerality that give focus and energy. Those demonstrating great character, balance with good acidity and plush tannins.",
  notes = "Adapted from [a beautiful table by Abdoul Madjid.](https://github.com/AbdoulMa/RStudio-Table-Contest-2021)",
  width = c(1, 4, 5, 3, 5, 6, 3, 2, 2)) |>
  theme_void() |>
  format_tt(j = 8, fn = scales::label_currency()) |>
  format_tt(j = 9, fn = scales::label_percent(scale = 1)) |>
  format_tt("notes", markdown = TRUE) |>
  style_tt(align = "c", alignv = "m") |>
  style_tt(i = 0, line = "b", line_width = 0.2) |>
  style_tt(i = 1:nrow(tbl), j = 9, color = "burgundy", bold = TRUE, fontsize = 1.5) |>
  plot_tt(i = 0, j = 2:9, images = header_icons, height = 2) |>
  plot_tt(i = seq_len(nrow(tbl)), j = 1, images = bottle_images_data, height = 4) |>
  theme_html(class = "table table-hover table-responsive-sm caption-top")

save_tt(tab, output = "wines.html", overwrite = TRUE)
