

#' Style a Tiny Table for HTML Bootstrap output
#'
#' Applies Bootstrap styling to specific cells in an HTML table. It allows 
#' customization of cell styles using CSS.
#'
#' @param x A tiny table generated by the `tt()` function.
#' @param i An integer vector specifying the rows to be styled. If missing, 
#'   defaults to all rows in the table.
#' @param j An integer vector specifying the columns to be styled. If missing, 
#'   defaults to all columns in the table.
#' @param css A vector of CSS style declarations to be applied. Each element 
#'   corresponds to a cell defined by `i` and `j`.
#' @param css_rule A string with complete CSS rules that apply to the table class specified using the `theme` argument of the `tt()` function.
#' 
#' @return Returns the modified HTML table object with added Bootstrap styling.
#'
#' @export
style_bootstrap <- function(x, i, j, css = NULL, css_rule = NULL) {
  out <- x

  if (!inherits(x, "tinytable_bootstrap")) return(x)
  if (missing(i)) i <- seq_len(attr(x, "nrow"))
  if (missing(j)) j <- seq_len(attr(x, "ncol"))
  assert_integerish(i, lower = 1, null.ok = TRUE)
  assert_integerish(j, lower = 1, null.ok = TRUE)
  assert_string(css_rule, null.ok = TRUE)

  if (!is.null(css_rule)) {
    out <- bootstrap_setting(out, css_rule, component = "css")
  }
  # after css_rule
  if (is.null(css)) return(out)

  # JS 0-indexing
  j <- j - 1
  i <- i - 1 + attr(x, "nhead")

  id <- get_id(stem = "tinytable_css_")

  # CSS style for cell
  css_start <- sprintf(".table td.%s { ", id)
  css_complete <- paste(c(css_start, paste0(css, collapse="; "), "}"), collapse = " ")
  out <- bootstrap_setting(out, css_complete, component = "css")

  # Listener applies the styling to columns
  for (row in i) {
    for (col in j) {
      listener <- sprintf("window.addEventListener('load', function () { styleCell_%s(%s, %s, '%s') })", id, row, col, id)
      out <- bootstrap_setting(out, listener, component = "cell")
    }
  }

  # Changing function names for JS
  out <- gsub("styleCell_\\w+\\(", paste0("styleCell_", id, "("), out)

  class(out) <- class(x)
  return(out)
}

