

#' Style a Tiny Table for HTML Bootstrap output
#'
#' Applies Bootstrap styling to specific cells in an HTML table. It allows 
#' customization of cell styles using CSS.
#'
#' @param x A tiny table generated by the `tt()` function.
#' @param i An integer vector specifying the rows to be styled. If missing, 
#'   defaults to all rows in the table.
#' @param j An integer vector specifying the columns to be styled. If missing, 
#'   defaults to all columns in the table.
#' @param css A vector of CSS style specifications to be applied. Each element 
#'   corresponds to a cell defined by `i` and `j`.
#' @param colspan Defines the number of columns a cell should span. When this argument is used, `i` and `j` must be single integers.
#' 
#' @return Returns the modified HTML table object with added Bootstrap styling.
#'
#' @export
style_bootstrap <- function(x,
                            i,
                            j,
                            css,
                            colspan) {

  if (missing(i)) i <- seq_len(attr(x, "nrow"))
  if (missing(j)) j <- seq_len(attr(x, "ncol"))
  assert_integerish(i, lower = 1, null.ok = TRUE)
  assert_integerish(j, lower = 1, null.ok = TRUE)

  # JS 0-indexing,
  j <- j - 1
  i <- i - 1 + attr(x, "nhead")

  out <- x

  id <- get_id(stem = "tinytable_css_")

  # css style
  css <- build_bootstrap_css(css_vector = css, id = id, type = "cell")
  out <- bootstrap_setting(out, css, component = "css")

  # listener applies the styling to columns
  for (row in i) {
    for (col in j) {
      listener <- sprintf("window.addEventListener('load', function () { styleCell_blahblahblah(%s, %s, '%s') })", row, col, id)
      out <- bootstrap_setting(out, listener, component = "cell")
    }
  }

  # styling function in JS must have different names when there is more than one table on a page.
  # we need to change this here AND in the `tt_bootstrap()`, because otherwise the listener calls will not be changed or will not match the styleCell ID.
  out <- gsub("styleCell_\\w+\\(", paste0("styleCell_", id, "("), out)

  class(out) <- class(x)

  return(out)
}



build_bootstrap_css <- function(css_vector, id, type = "cell") {
  if (type == "row") {
    out <- sprintf(".table tr.%s td {", id)
  } else if (type == "cell") {
    out <- sprintf(".table td.%s {", id)
  }
  out <- c(out, paste0(css_vector, ";"))
  out <- paste(out, collapse = " ")
  out <- paste(out, "}")
  return(out)
}
