# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"
  _R_CHECK_TESTS_NLINES_: 0
  R_NOT_CRAN: true
  R_GH: true
  GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

jobs:
  ci:
    strategy:
      matrix:
        include:
          # - {os: macOS-latest,   r: 'release'}
          # - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', depends_only: TRUE}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel'}
          - {os: ubuntu-latest,   r: '4.1.3'}

    runs-on: ${{ matrix.os }}

    env:
      _R_CHECK_FORCE_SUGGESTS_: "false"
      _R_CHECK_TESTS_NLINES_: 0
      R_NOT_CRAN: true
      R_GH: true
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11' # The pandoc version to download (if necessary) and use.

      - name: Get Script
        run: curl -OLs https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh

      - name: Bootstrap
        run: ./run.sh bootstrap

      - name: png (for svglite)
        run: sudo apt update -qq && sudo apt install --yes --no-install-recommends libpng-dev

      - name: svglite from source
        run: Rscript -e "bspm::disable();install.packages('svglite', from = 'source');bspm::enable()"

      - name: Dependencies
        run: ./run.sh install_all

      - name: tinysnapshot dev
        run: ./run.sh install_github vincentarelbundock/tinysnapshot

      - name: install tinytex
        run: Rscript -e "tinytex::install_tinytex()"

      - name: Test
        run: ./run.sh run_tests
          
      # - name: Coverage
      #   if: ${{ matrix.os == 'ubuntu-latest' }}
      #   run: ./run.sh coverage
